name: Publish to NPM

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  check:
    uses: ./.github/workflows/check.yml

  publish:
    runs-on: ubuntu-latest
    needs: check

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
